# Generated by Django 5.1.6 on 2025-03-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateField(),
        ),
    ]
