# Generated by Django 5.1.5 on 2025-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0004_alter_meallog_calories_dietgoal_streaktracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
